apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::274758582534:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UVFU2KWU7SMG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::274758582534:role/UdacityFlaskDeployCBKubectlRole
      username: build     
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-23T21:54:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1726"
  uid: d0e7f762-4c3a-41d8-9830-2c6b13faf132
